PageViewer/PageViewer/Models/Block.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PageViewer.Models
{
    public class Block
    {
        public string Type { get; set; }
        public string Identifier { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
    }
}

PageViewer/PageViewer/Models/ErrorViewModel.cs
using System;

namespace PageViewer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PageViewer/PageViewer/Models/PageDirectory.cs
using PageViewer.Data;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PageViewer.Models
{
    public class PageDirectory
    {
        public static int pageidcounter = 0;

        public static PageDirectory BuildRootPageDirectory(DirectoryInfo rdi)
        {
            pageidcounter = 0;
            PageDirectory rpd = new PageDirectory(rdi);
            return rpd;
        }

        public DirectoryInfo _di;

        public PageDirectory(DirectoryInfo di)
        {
            Count = 0;

            PageViews = new List<PageView>();
            PageDirectories = new List<PageDirectory>();

            _di = di;

            Name = _di.Name;

            foreach (DirectoryInfo sdi in _di.GetDirectories())
            {
                PageDirectory spd = new PageDirectory(sdi);
                if (spd.PageViews.Count > 0 ||
                    spd.PageDirectories.Count > 0)
                {
                    PageDirectories.Add(spd);
                    Count += spd.Count;
                }
            }

            foreach (FileInfo fi in _di.GetFiles("*.page"))
            {
                Page page = new Page();
                page.LoadFileAsync(fi, "IPS");
                PageViews.Add(page.GetPageView(pageidcounter++));
                Count++;
            }
        }
        public PageDirectory()
        {
            PageViews = new List<PageView>();
            PageDirectories = new List<PageDirectory>();
        }

        public PageDirectory ApplyFilter(string filter)
        {
            PageDirectory fpd = new PageDirectory();
            fpd._di = _di;
            fpd.Name = _di.Name;

            foreach (PageDirectory spd in PageDirectories)
            {
                PageDirectory sfpd = spd.ApplyFilter(filter);
                if (sfpd.PageViews.Count > 0 ||
                    sfpd.PageDirectories.Count > 0)
                {
                    fpd.PageDirectories.Add(sfpd);
                    fpd.Count += sfpd.Count;
                }
            }

            foreach (PageView spv in PageViews)
            {
                if (spv.Name.ToUpper().Contains(filter.ToUpper()))
                {
                    fpd.PageViews.Add(spv);
                    fpd.Count++;
                }
            }

            return fpd;
        }

        public PageView FindPageView(int id)
        {
            foreach (PageView pv in PageViews)
            {
                if (pv.ID == id)
                {
                    return pv;
                }
            }

            foreach (PageDirectory pd in PageDirectories)
            {
                PageView pv = pd.FindPageView(id);
                if (pv != null)
                {
                    return pv;
                }
            }

            return null;
        }

        public int Count { get; set; }
        public string Name { get; set; }
        public List<PageView> PageViews { get; set; }
        public List<PageDirectory> PageDirectories { get; set; }
    }
}

PageViewer/PageViewer/Models/PageView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PageViewer.Models
{
    public class PageView
    {
        public PageView()
        {
            Blocks = new List<Block>();
        }

        public int ID { get; set; }
        public string Name { get; set; }
        public List<Block> Blocks { get; set; }
    }
}

PageViewer/PageViewer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PageViewer.Data;
using PageViewer.Models;

namespace PageViewer.Controllers
{
    public class HomeController : Controller
    {
        // GET: PageViews
        public ActionResult Index(string searchString)
        {
            PageDirectory availablepageviews = GetAvailablePageViews();
            return View(availablepageviews.ApplyFilter(searchString != null?searchString:string.Empty));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private static PageDirectory _RootPD;

        public static PageDirectory GetAvailablePageViews()
        {
            if (_RootPD == null)
            {
                FileInfo fi = new FileInfo(typeof(PageView).Assembly.Location);

                string simupagepath = fi.Directory.FullName + @"\wwwroot\simupages\";

                DirectoryInfo pdi = new DirectoryInfo(simupagepath);

                _RootPD = PageDirectory.BuildRootPageDirectory(pdi);
            }

            return _RootPD;
        }

    }
}

PageViewer/PageViewer/Controllers/PageViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PageViewer.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PageViewer.Controllers
{
    public class PageViewController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index(string searchString)
        {
            PageDirectory availablepageviews = HomeController.GetAvailablePageViews();
            return View(availablepageviews.ApplyFilter(searchString != null ? searchString : string.Empty));
        }

        // GET: Components/Details/5
        public ActionResult Details(int id)
        {
            PageDirectory availablepageviews = HomeController.GetAvailablePageViews();
            PageView pv = availablepageviews.FindPageView(id);
            return View(pv);
        }
    }
}

PageViewer/PageViewer/Views/Home/Index.cshtml
@model PageDirectory


@{
    ViewData["Title"] = "Home Page (My change)";
}

<h1>Pages</h1>

<br />

@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}

<br />

<h3>Total pages found = @Model.Count</h3>

<ul id="myUL">
    @Html.Raw(GetTree(@Model, true))
</ul>

<script>
    var toggler = document.getElementsByClassName("caret");
    var i;

    for (i = 0; i < toggler.length; i++) {
        toggler[i].addEventListener("click", function () {
            this.parentElement.querySelector(".nested").classList.toggle("active");
            this.classList.toggle("caret-down");
        });
    }
</script>

@functions{
    public string GetTree(PageDirectory pd, bool hideroot = false)
    {
        string treeHTML = string.Empty;

        if (!hideroot)
        {
            treeHTML += "<li>";
            treeHTML += "<span class=\"caret\">";
            treeHTML += pd.Name;
            treeHTML += "</span>";

            treeHTML += "<ul class=\"nested active\">";

            foreach (PageDirectory spd in pd.PageDirectories)
            {
                treeHTML += GetTree(spd);
            }

            foreach (PageView spv in pd.PageViews)
            {
                treeHTML += GetTree(spv);
            }

            treeHTML += "</ul>";

            treeHTML += "</li>";
        }
        else
        {
            foreach (PageDirectory spd in pd.PageDirectories)
            {
                treeHTML += GetTree(spd);
            }
        }

        return treeHTML;
    }

    public string GetTree(PageView pv)
    {
        string treeHTML = string.Empty;

        treeHTML += "<li><a href=\"./PageView/Details/" + pv.ID + "\">";
        treeHTML += pv.Name;
        treeHTML += "</a></li>";

        return treeHTML;
    }
}

PageViewer/PageViewer/Views/PageView/Details.cshtml
@model PageView


@{
    ViewData["Title"] = "Page View";
}

<h1>@Model.Name</h1>

<br />

<svg width="1000" height="1000">
    <defs id="defs4">
        <linearGradient id="linearGradient5255">
            <stop style="stop-color:#ffcc00;stop-opacity:1;" offset="0" id="stop5257" />
            <stop style="stop-color:#c19a00;stop-opacity:1;" offset="1" id="stop5259" />
        </linearGradient>
    </defs>

    <rect style="fill:url(#linearGradient5255)" id="rect3769" width="990" height="990" x="10" y="10" ry="10" rx="10"/>
</svg>

PageViewer/PageViewer/Views/PageView/Index.cshtml
@model PageDirectory


@{
    ViewData["Title"] = "Page View COOL";
}

<h1>Pages</h1>

<br />

@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}

<br />

<h3>Total pages found = @Model.Count</h3>

<ul id="myUL">
    @Html.Raw(GetTree(@Model, true))
</ul>

<script>
    var toggler = document.getElementsByClassName("caret");
    var i;

    for (i = 0; i < toggler.length; i++) {
        toggler[i].addEventListener("click", function () {
            this.parentElement.querySelector(".nested").classList.toggle("active");
            this.classList.toggle("caret-down");
        });
    }
</script>

@functions{
    public string GetTree(PageDirectory pd, bool hideroot = false)
    {
        string treeHTML = string.Empty;

        if (!hideroot)
        {
            treeHTML += "<li>";
            treeHTML += "<span class=\"caret\">";
            treeHTML += pd.Name;
            treeHTML += "</span>";

            treeHTML += "<ul class=\"nested active\">";

            foreach (PageDirectory spd in pd.PageDirectories)
            {
                treeHTML += GetTree(spd);
            }

            foreach (PageView spv in pd.PageViews)
            {
                treeHTML += GetTree(spv);
            }

            treeHTML += "</ul>";

            treeHTML += "</li>";
        }
        else
        {
            foreach (PageDirectory spd in pd.PageDirectories)
            {
                treeHTML += GetTree(spd);
            }
        }

        return treeHTML;
    }

    public string GetTree(PageView pv)
    {
        string treeHTML = string.Empty;

        treeHTML += "<li><a href=\"./PageView/Details/" + pv.ID + "\">";
        treeHTML += pv.Name;
        treeHTML += "</a></li>";

        return treeHTML;
    }
}

PageViewer/PageViewer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PageViewer</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PageViewer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PageView" asp-action="Index">PageView</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PageViewer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>